import os
from .info import *
from .intent_slot_info import *


BERTTAG_SKETCH_PLACEHOLDER = '<mask>'
LBMS_TAG_CLASSES = len(ONTOLOGY) - 5  # Excluding the Intents
LMSB_TAG_MAX_LENGTH = 60

BERTTAG_CLASSES = len(ONTOLOGY) - 5  # Excluding the Intents
BERTTAG_THRESHOLD = 0.5
BERTTAG_DROPOUT = 0.2

BERTTAG_LR = 1e-5
BERTTAG_BEAM = 5
BERTTAG_MAX_LENGTH = 60
BERTTAG_TGT_MAX_LENGTH = BERTTAG_MAX_LENGTH
BERTTAG_EPOCHS = 50
BERTTAG_PRINT_EVERY = 5
BERTTAG_SIZE = 'base'
BERTTAG_BATCH_SIZE = 5
BERTTAG_HATE_PRETRAIN = 0
BERTTAG_EXPERIMENT_NAME = f'checkpoints_{BERTTAG_SIZE}_cls_lr{BERTTAG_LR}_batch{BERTTAG_BATCH_SIZE}_th{BERTTAG_THRESHOLD}_maxLen{BERTTAG_MAX_LENGTH}_dp{BERTTAG_DROPOUT}/'
BERTTAG_MODEL_DIR = LOG_DIR + 'litberttag/'
BERTTAG_CHECKPOINT_DIR = BERTTAG_MODEL_DIR + BERTTAG_EXPERIMENT_NAME

BERTTAG_RES_FILE = BERTTAG_MODEL_DIR + 'scores.tsv'

BERTTAG_AAA_CKPT = BERTTAG_CHECKPOINT_DIR + 'default/version_SEED/checkpoints/'

if not os.path.exists(BERTTAG_MODEL_DIR):
	os.makedirs(BERTTAG_MODEL_DIR)

BERTTAG_PREDICTIONS_FILE = BERTTAG_MODEL_DIR + f'{BERTTAG_EXPERIMENT_NAME[:-1]}.res.tsv'

BERTTAG_AAA_ANSWER_FILES_DIR = BERTTAG_CHECKPOINT_DIR + 'aaa_answers/'
if not os.path.exists(BERTTAG_AAA_ANSWER_FILES_DIR):
	os.makedirs(BERTTAG_AAA_ANSWER_FILES_DIR)
BERTTAG_AAA_ANSWER_FILES = [f'{BERTTAG_AAA_ANSWER_FILES_DIR}{fname}' for fname in AAA_FILES] 
