import os
from .info import *

LMSB_SKETCH_PLACEHOLDER = '<mask>'


LMSB_LR = 2e-5
LMSB_BEAM = 5
LMSB_MAX_LENGTH = 50
LMSB_TGT_MAX_LENGTH = LMSB_MAX_LENGTH
LMSB_EPOCHS = 60
LMSB_PRINT_EVERY = 5
LMSB_SIZE = 'base'
LMSB_BATCH_SIZE = 16
LMSB_ENCODE_INPUT_TWICE = True
LMSB_HATE_PRETRAIN = 0
LMSB_EXPERIMENT_NAME = f'checkpoints_{LMSB_SIZE}_2lm_encInp{LMSB_ENCODE_INPUT_TWICE}_hp{LMSB_HATE_PRETRAIN}_lr{LMSB_LR}_batch{LMSB_BATCH_SIZE}_beam{LMSB_BEAM}_maxLen{LMSB_MAX_LENGTH}/'
LMSB_MODEL_DIR = LOG_DIR + 'litmsbart/'
LMSB_CHECKPOINT_DIR = LMSB_MODEL_DIR + LMSB_EXPERIMENT_NAME

LMSB_RES_FILE = LMSB_MODEL_DIR + 'scores.tsv'

LMSB_AAA_CKPT = LMSB_CHECKPOINT_DIR + 'default/version_SEED/checkpoints/'

if not os.path.exists(LMSB_MODEL_DIR):
	os.makedirs(LMSB_MODEL_DIR)
LMSB_PREDICTIONS_FILE = LMSB_MODEL_DIR + f'{LMSB_EXPERIMENT_NAME[:-1]}.res.tsv'

LMSB_AAA_ANSWER_FILES_DIR = LMSB_CHECKPOINT_DIR + 'aaa_answers/'
if not os.path.exists(LMSB_AAA_ANSWER_FILES_DIR):
	os.makedirs(LMSB_AAA_ANSWER_FILES_DIR)
LMSB_AAA_ANSWER_FILES = [f'{LMSB_AAA_ANSWER_FILES_DIR}{fname}' for fname in AAA_FILES]
