from paead_info.info import *
from paead_info.intent_slot_info import *
import os


S2I_NUM_CLASSES = len(RULES)
S2I_MAX_EPOCHS = 50
S2I_BATCH_SIZE = 32
S2I_LEARNING_RATE = 0.00001
S2I_MAX_LENGTH = 256
S2I_PRINT_EVERY = 10
S2I_INTENT_LOSS_WEIGHT = 1.0
S2I_BINARY_INTENT_LOSS_WEIGHT = -0.2
S2I_HATE_PRETRAIN = 0
S2I_OPTIMIZER = 'adam'

S2I_EXPERIMENT_NAME = f's2i_iw{S2I_INTENT_LOSS_WEIGHT}_bw{S2I_BINARY_INTENT_LOSS_WEIGHT}_hp{S2I_HATE_PRETRAIN}_lr{S2I_LEARNING_RATE}_bs{S2I_BATCH_SIZE}_{S2I_OPTIMIZER}'
if not USE_ATTRIBUTES:
	S2I_EXPERIMENT_NAME += '_noAttributes'
S2I_MODEL_DIR = LOG_DIR + 's2i/'
# S2I_MODEL_FILE = S2I_MODEL_DIR + f'{EXPERIMENT_NAME}.pt'
S2I_CHECKPOINT_DIR = S2I_MODEL_DIR + S2I_EXPERIMENT_NAME

